---
driver:
  name: vagrant

provisioner:
  name: shell
  data_path: .
  script: test/fixtures/bootstrap.sh

verifier:
  ruby_bindir: /opt/sensu/embedded/bin

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
